version: '3.4'

services:
  productdb:
    image: mongo

  product.api:
    image: ${DOCKER_REGISTRY-}productapi
    build:
      context: .
      dockerfile: Services/Product/Product.API/Dockerfile



volumes:
  mongo_data: